### PR TITLE
Fix layout and button click for iOS Counter sample

### LINKED ISSUE #903: iOS flexbox appears to be broken
Views appear to be correctly added to the hierarchy but they have no size or position.

Screen Shot 2023-04-11 at 1 53 07 PM

Screen Shot 2023-04-11 at 1 59 00 PM

### LINKED ISSUE #930: Counter sample broken on iOS
The selector isn't working from Kotlin and you get a crash that it's not found.

```
2023-04-11 20:39:32.787701-0700 CounterApp[66576:2686290] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[CounterKt_kobjcc0 clicked]: unrecognized selector sent to instance 0x6000027a5fb0'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000018040e7c8 __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x0000000180051144 objc_exception_throw + 56
	2   CoreFoundation                      0x000000018041d47c +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
	3   CoreFoundation                      0x00000001804126c8 ___forwarding___ + 1308
	4   CoreFoundation                      0x0000000180414b4c _CF_forwarding_prep_0 + 92
	5   UIKitCore                           0x000000010c85f6c8 -[UIApplication sendAction:to:from:forEvent:] + 96
	6   UIKitCore                           0x000000010c2154bc -[UIControl sendAction:to:forEvent:] + 108
	7   UIKitCore                           0x000000010c215800 -[UIControl _sendActionsForEvents:withEvent:] + 268
	8   UIKitCore                           0x000000010c21242c -[UIButton _sendActionsForEvents:withEvent:] + 120
	9   UIKitCore                           0x000000010c2144bc -[UIControl touchesEnded:withEvent:] + 396
	10  UIKitCore                           0x000000010c894888 -[UIWindow _sendTouchesForEvent:] + 900
	11  UIKitCore                           0x000000010c895d30 -[UIWindow sendEvent:] + 3184
	12  UIKitCore                           0x000000010c873fe0 -[UIApplication sendEvent:] + 692
	13  UIKit                               0x000000010702b0b4 -[UIApplicationAccessibility sendEvent:] + 92
	14  UIKitCore                           0x000000010c8f196c __dispatchPreprocessedEventFromEventQueue + 6824
	15  UIKitCore                           0x000000010c8f35d0 __processEventQueue + 5612
	16  UIKitCore                           0x000000010c8ec4ac __eventFetcherSourceCallback + 220
	17  CoreFoundation                      0x000000018037318c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
	18  CoreFoundation                      0x00000001803730d4 __CFRunLoopDoSource0 + 172
	19  CoreFoundation                      0x0000000180372844 __CFRunLoopDoSources0 + 232
	20  CoreFoundation                      0x000000018036ceb0 __CFRunLoopRun + 756
	21  CoreFoundation                      0x000000018036c7a4 CFRunLoopRunSpecific + 584
	22  GraphicsServices                    0x0000000188ff7c98 GSEventRunModal + 160
	23  UIKitCore                           0x000000010c85a37c -[UIApplication _run] + 868
	24  UIKitCore                           0x000000010c85e374 UIApplicationMain + 124
	25  CounterApp                          0x0000000104889f4c main + 64
	26  dyld                                0x00000001048e5fa0 start_sim + 20
	27  ???                                 0x00000001049cdf28 0x0 + 4372356904
	28  ???                                 0xd50d000000000000 0x0 + 15351926704775888896
)
```

### PR DESCRIPTION
**Pull request by DylanSale**
Closes #930. Closes #903.

Mostly slimilar to my previous PR #951 - see that for more details on the other changes, but I removed the `NSLayoutConstraints`. They were breaking nested Rows and Columns and it turns out it was just over complicating things. 

Tracking through the existing code it was clear that the `UIViewFlexContainer` was mostly working as intended (aside from using top instead of bottom for the content size). The main layout issue was that the UIStackView that contained the root Compose view was using `.center` instead of `.fill` for the alignment, which doesn't work at the boundary between the Flexbox and NSAutoLayout code because the Flexbox and NSAutoLayout treat "intrinsicSize" differently - UIStackView with alignment `.center` makes it shrink the content to the minimum size (which is 0 for scrollviews), but the flex layouts will set it to wrap by default I believe.

I think the takeaway here is that the Compose root view should always just be set to fill the available space or have the frame set manually in the host view.

### CODE REVIEW

File: redwood-layout-uiview/src/commonMain/kotlin/app/cash/redwood/layout/uiview/UIViewFlexContainer.kt [hunk 1]
```diff
@@ -135,7 +135,7 @@ internal class UIViewFlexContainer(
       setContentSize(
         CGSizeMake(
           width = container.items.maxOfOrNull { it.right } ?: 0.0,
-          height = container.items.maxOfOrNull { it.top } ?: 0.0,
+          height = container.items.maxOfOrNull { it.bottom } ?: 0.0,
```
Comment (chrisbanes) [inline redwood-layout-uiview/src/commonMain/kotlin/app/cash/redwood/layout/uiview/UIViewFlexContainer.kt:138]: I don't know UIKit at all, but is `it.top` guaranteed to be 0 here? Do we need to do `bottom - top`?

**Review by chrisbanes — APPROVED** [review]

File: redwood-layout-uiview/src/commonMain/kotlin/app/cash/redwood/layout/uiview/UIViewFlexContainer.kt (hunk 1 above)
Comment (DylanSale) [reply redwood-layout-uiview/src/commonMain/kotlin/app/cash/redwood/layout/uiview/UIViewFlexContainer.kt:138]: In UIKit the `top` of the bounds is 0 and `bottom` goes into the positive y axis, so the height is the largest bottom value.

Using `top` here caused the contentSize to be one view short, making items get cut off (more visible if you had a large item on the bottom because iOS adds a default content inset for the horizontal home indicator).

File: samples/counter/ios-shared/src/commonMain/kotlin/com/example/redwood/counter/ios/IosButton.kt [hunk 2]
```diff
@@ -24,7 +24,7 @@ import platform.UIKit.UIControlStateNormal
 import platform.UIKit.UIView
 import platform.objc.sel_registerName
 
-internal class IosButton : Button<UIView> {
+class IosButton : Button<UIView> {
```
Comment (JakeWharton) [inline samples/counter/ios-shared/src/commonMain/kotlin/com/example/redwood/counter/ios/IosButton.kt:28]: Until we get #536 for iOS:

```suggestion
// NOTE: This class must be public for the click selector to work.
class IosButton : Button<UIView> {
```

**Review by JakeWharton — APPROVED** [review]
Thanks!

**Comment by JakeWharton** [comment]
Setting to auto-merge since it seems _really_ low-risk in terms of changes to the shared layout engine. If you have any comments @underscoretang we can address in a follow-up.
