### PR TITLE
Fix a host crash in LazyListUpdateProcessor

### LINKED ISSUE #2172: UncaughtTreehouseException: toIndex = 1
Our LazyList code is crashing.

```
com.squareup.cash.treehouse.android.UncaughtTreehouseException: toIndex = 1
        at java.util.AbstractList.subListRangeCheck(AbstractList.java:507)
        at java.util.ArrayList.subList(ArrayList.java:1125)
        at app.cash.redwood.lazylayout.widget.SparseList.addRange(SparseList:126)
        at app.cash.redwood.lazylayout.widget.LazyListUpdateProcessor.maybeShiftLoadedWindow(LazyListUpdateProcessor:311)
        at app.cash.redwood.lazylayout.view.ViewLazyList.margin(ViewLazyList:174)
        at app.cash.redwood.lazylayout.widget.LazyListUpdateProcessor.onEndChanges(LazyListUpdateProcessor:174)
        at app.cash.redwood.lazylayout.view.ViewLazyList.onEndChanges(ViewLazyList:210)
        at app.cash.redwood.protocol.host.ProtocolBridge.sendChanges(ProtocolBridge:151)
        at app.cash.redwood.treehouse.ViewContentCodeBinding.receiveChangesOnUiDispatcher(ViewContentCodeBinding:415)
        at app.cash.redwood.treehouse.ViewContentCodeBinding.access$receiveChangesOnUiDispatcher(ViewContentCodeBinding:297)
        at app.cash.redwood.treehouse.ViewContentCodeBinding$sendChanges$1.invokeSuspend(ViewContentCodeBinding:378)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask:104)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7941)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1019)
```

### PR DESCRIPTION
**Pull request by swankjesse**
I introduced a bug in the mechanism that attempts to replace animated inserts and removes with update-in-place transitions.

The crash occurs when the before window shrinks while the total number of elements is growing. The previous code naively assumed the before window shrinking would always be a scroll, but it can coincide with a content change.

Closes: https://github.com/cashapp/redwood/issues/2172

---

- [x] `CHANGELOG.md`'s "Unreleased" section has been updated, if applicable.

### CODE REVIEW

File: redwood-lazylayout-widget/src/commonTest/kotlin/app/cash/redwood/lazylayout/widget/LazyListUpdateProcessorTest.kt [hunk 1]
```diff
@@ -566,6 +566,89 @@ class LazyListUpdateProcessorTest {
...
+    processor.items.insert(0, "C")
+    processor.items.insert(1, "D")
+    processor.items.insert(2, "E")
+    processor.items.insert(3, "F")
+    processor.items.insert(4, "G")
+    processor.items.insert(5, "H")
+    processor.items.insert(6, "I")
+    processor.onEndChanges()
+    processor.scrollTo(0, 12)
+    assertThat(processor.toString()).isEqualTo(". . C D E Fv2 G H I . . .")
```
Comment (swankjesse) [inline redwood-lazylayout-widget/src/commonTest/kotlin/app/cash/redwood/lazylayout/widget/LazyListUpdateProcessorTest.kt:596]: The `v2` after `F` here means there was an update-in-place, rather than a structural change. I’d like to do a follow-up to make these all say `v2`, which is how we reduce the glitchy animations in update processing.

File: redwood-lazylayout-widget/src/commonTest/kotlin/app/cash/redwood/lazylayout/widget/LazyListUpdateProcessorTest.kt [hunk 2]
```diff
@@ -566,6 +566,89 @@ class LazyListUpdateProcessorTest {
...
+    processor.items.insert(1, "D")
+    processor.items.insert(2, "E")
+    processor.items.insert(3, "F")
+    processor.items.insert(4, "G")
+    processor.items.insert(5, "H")
+    processor.items.insert(6, "I")
+    processor.itemsAfter(2)
+    processor.onEndChanges()
+    processor.scrollTo(0, 12)
+    assertThat(processor.toString()).isEqualTo(". . . Cv2 D E F G H I . .")
```
Comment (swankjesse) [inline redwood-lazylayout-widget/src/commonTest/kotlin/app/cash/redwood/lazylayout/widget/LazyListUpdateProcessorTest.kt:633]: Same v2 thing.

**Review by dnagler — APPROVED** [review]
Good catch!

**Review by colinmarsch — APPROVED** [review]
Thanks for the quick fix! The tests look great!
