### PR TITLE
fix ButtonBinding.swift click action error！

### LINKED ISSUE #1506: test-app ios project ButtonBinding logic error
Button interface onClick(onClick: (() -> Void)? = nil)
root action #selector  is  clicked() call interface method onClick，should is property onClick call

### PR DESCRIPTION
**Pull request by hxxyyangyong**
The interface method of Button is implemented in ButtonBinding, but the root button executes the interface method again, resulting in the inability to call back the Unit in Kotlin. Here, the assigned attribute OnClick should be called.

Closes #1506

### CODE REVIEW

**Comment by hxxyyangyong** [comment]
@JakeWharton

File: test-app/ios-uikit/TestApp/ButtonBinding.swift [hunk 1]
```diff
@@ -48,7 +48,7 @@ class ButtonBinding: Button {
     
     @objc func clicked() {
         if (self.onClick != nil) {
-            self.onClick()
+            self.onClick?()
```
Comment (hoc081098) [inline test-app/ios-uikit/TestApp/ButtonBinding.swift]: I think `self.onClick?()` without `if` is better 😂

Comment (hxxyyangyong) [reply test-app/ios-uikit/TestApp/ButtonBinding.swift]: This has nothing to do with the problem itself. Prioritize solving the actual problem. The main reason is that the calling method is wrong. Adding if is more standard.

Comment (JakeWharton) [reply test-app/ios-uikit/TestApp/ButtonBinding.swift]: But why would we execute the `if` when adding the conditional chaining operator also performs a conditional? Aren't the two equivalent thus redundant?

**Review by JakeWharton — APPROVED** [review]
