### PR TITLE
Change our tree to be custom nodes instead of raw widgets

### LINKED ISSUE #998: `LayoutModifier`s do not work outside of protocol usage
The only call to `onLayoutModifierUpdated` in the codebase is in `ProtocolBridge`.

Thankfully(?) I've been noodling on redesigning how notification to the parent occurs in order to fix #785 via a protocol change, so this issue will track that change which will be done first.

This may also be the source of some of the bugs in the counter sample.

### PR DESCRIPTION
**Pull request by JakeWharton**
We already were faking half of the tree with the synthetic children widgets before. Now we keep children nodes which do the same thing as before but are joined by widget nodes which wrap a widget and provide access to the parent children. This is used to notify the parent children when any child's layout modifiers have changed.

Closes #998

### CODE REVIEW

File: redwood-compose/src/commonMain/kotlin/app/cash/redwood/compose/WidgetApplier.kt [hunk 1]
```diff
@@ -59,37 +64,102 @@ internal class WidgetApplier<W : Any>(
...
+/** @suppress For generated code usage only. */
+@RedwoodCodegenApi
+public sealed interface Node<W : Any>
+
+/**
+ * A node which wraps a [Widget] and also holds onto the [Widget.Children] in which the widget
+ * is placed. The generics of this class are a little funky in order to avoid casts of the widget
+ * in the generated composables.
+ *
+ * @suppress For generated code usage only.
```
Comment (swankjesse) [inline redwood-compose/src/commonMain/kotlin/app/cash/redwood/compose/WidgetApplier.kt:116]: Why `@suppress` ?

File: redwood-compose/src/commonMain/kotlin/app/cash/redwood/compose/WidgetApplier.kt [hunk 2]
```diff
@@ -59,37 +64,102 @@ internal class WidgetApplier<W : Any>(
...
+  public companion object {
+    public val SetLayoutModifiers: WidgetNode<*, *>.(LayoutModifier) -> Unit = {
+      widget.layoutModifiers = it
+      container?.onLayoutModifierUpdated()
+    }
+  }
+}
+
+/**
+ * A synthetic widget which allows the applier to differentiate between multiple groups of children.
```
Comment (swankjesse) [inline redwood-compose/src/commonMain/kotlin/app/cash/redwood/compose/WidgetApplier.kt:133]: These descriptions are really helpful

File: redwood-compose/src/commonMain/kotlin/app/cash/redwood/compose/WidgetApplier.kt [hunk 3]
```diff
@@ -59,37 +64,102 @@ internal class WidgetApplier<W : Any>(
...
+ *
+ * Compose's tree assumes each node only has single list of children. Or, put another way, even if
+ * you apply multiple children Compose treats them as a single list of child nodes. In order to
+ * differentiate between these children lists we introduce synthetic nodes. Every real node which
+ * supports one or more groups of children will have one or more of these synthetic nodes as its
+ * direct descendants. The nodes which are produced by each group of children will then become the
+ * descendants of those synthetic nodes.
+ *
+ * This node has two valid states:
```
Comment (swankjesse) [inline redwood-compose/src/commonMain/kotlin/app/cash/redwood/compose/WidgetApplier.kt:142]: This is a tricky process, but the description makes it nice & clear

File: redwood-compose/src/commonMain/kotlin/app/cash/redwood/compose/WidgetApplier.kt [hunk 4]
```diff
@@ -59,37 +64,102 @@ internal class WidgetApplier<W : Any>(
...
+  private var _children: Widget.Children<W>?,
+) : Node<W> {
+  constructor(accessor: (Widget<W>) -> Widget.Children<W>) : this(accessor, null)
+  constructor(children: Widget.Children<W>) : this(null, children)
+
+  val children: Widget.Children<W> get() = _children!!
+
+  fun attachTo(parent: Widget<W>) {
+    _children = checkNotNull(_accessor).invoke(parent)
+    _accessor = null
```
Comment (swankjesse) [inline redwood-compose/src/commonMain/kotlin/app/cash/redwood/compose/WidgetApplier.kt]: Does accessor need `_` ?

**Review by swankjesse — APPROVED** [review]

File: redwood-compose/src/commonMain/kotlin/app/cash/redwood/compose/WidgetApplier.kt (hunk 1 above)
Comment (JakeWharton) [reply redwood-compose/src/commonMain/kotlin/app/cash/redwood/compose/WidgetApplier.kt:116]: Hides it from docs. No one should ever touch these things, but they're public because generated composable implementation must.

File: redwood-compose/src/commonMain/kotlin/app/cash/redwood/compose/WidgetApplier.kt (hunk 4 above)
Comment (JakeWharton) [reply redwood-compose/src/commonMain/kotlin/app/cash/redwood/compose/WidgetApplier.kt]: Nope! Forgot I added the function to attach rather than doing it at the call site.
