### PR TITLE
Make a CodeHost state machine

### LINKED ISSUE #1660: Make TreehouseApp more state machiney
Right now there’s a lot of implicit states in `TreehouseApp` and its current code. I’d like to make this more structured to support code crashes and restarts.

These are our states:

 * `Idle`
 * `Starting`: the ZiplineLoader is collecting code updates, waiting for a Zipline
 * `Running`: the ZiplineLoader is collecting code updates, and a Zipline is ready
 * `Crashed`: the ZiplineLoader is collecting code updates, but the most recent Zipline failed

I should be able to avoid `Stopping` and `Crashing` states by doing the corresponding cleanup asynchronously. Ie. when the app crashes it’ll ‘immediately’ transition to `Crashed` even though the old Zipline instance is still being torn down.

When the Zipline instance is updated via a hot-reload, it stays in the `Running` state without transition.

This is similar to [Guava’s service](https://github.com/google/guava/wiki/ServiceExplained). But unlike that interface I’d like to make `TreehouseApp` support multiple starts and stops. That way the consuming application doesn’t need to build its own lifecycles on top.

These states won’t necessarily appear in the public API anywhere, but functions to transition between them will:

 * start() - transition to `Starting` unless it’s `Starting` or `Running`.
 * stop() - transition to `Idle` immediately
 * restart() - transition to `Starting` unless it’s already there.

There’s no function to transition to `Crashed`; you have to do that by running bad code.

### PR DESCRIPTION
**Pull request by swankjesse**
This simplifies much of the internal complexity of TreehouseApp. We can also delete FakeCodeHost because the single implementation is suitable for unit testing.

Closes: https://github.com/cashapp/redwood/issues/1660

### CODE REVIEW

**Comment by swankjesse** [comment]
I’d like to add tests before reviewing this.

File: redwood-treehouse-host/src/commonTest/kotlin/app/cash/redwood/treehouse/FakeCodeSession.kt [hunk 1]
```diff
@@ -18,22 +18,32 @@ package app.cash.redwood.treehouse
 import app.cash.redwood.treehouse.CodeSession.Listener
 import app.cash.redwood.treehouse.CodeSession.ServiceScope
 import kotlinx.coroutines.CoroutineScope
+import kotlinx.coroutines.SupervisorJob
+import kotlinx.coroutines.cancel
+import kotlinx.coroutines.job
+import kotlinx.coroutines.launch
 import kotlinx.serialization.json.Json
 
 internal class FakeCodeSession(
```
Comment (swankjesse) [inline redwood-treehouse-host/src/commonTest/kotlin/app/cash/redwood/treehouse/FakeCodeSession.kt:27]: I think I can refactor the ZiplineCodeSession state management to share a lot more code with this fake.

File: redwood-treehouse-host/src/commonTest/kotlin/app/cash/redwood/treehouse/FakeOnBackPressedDispatcher.kt [hunk 2]
```diff
@@ -19,17 +19,27 @@ import app.cash.redwood.ui.Cancellable
...
 
   override fun addCallback(onBackPressedCallback: OnBackPressedCallback): Cancellable {
+    val id = nextCallbackId++
     mutableCallbacks += onBackPressedCallback
 
     return object : Cancellable {
+      var canceled = false
+
       override fun cancel() {
+        if (canceled) return
```
Comment (swankjesse) [inline redwood-treehouse-host/src/commonTest/kotlin/app/cash/redwood/treehouse/FakeOnBackPressedDispatcher.kt:39]: I don’t like that these are being canceled multiple times. It’s not a bug, but it’s inelegant.

File: redwood-treehouse-host/src/commonTest/kotlin/app/cash/redwood/treehouse/TreehouseAppContentTest.kt [hunk 3]
```diff
@@ -20,35 +20,59 @@ import assertk.assertThat
...
+    frameClockFactory = FakeFrameClock.Factory,
+  )
   private val codeListener = FakeCodeListener(eventLog)
   private val uiConfiguration = UiConfiguration()
 
+  @BeforeTest
+  fun setUp() {
+    runBlocking {
+      codeHost.start()
+      eventLog.takeEvent("codeHost.collectCodeUpdates()")
```
Comment (swankjesse) [inline redwood-treehouse-host/src/commonTest/kotlin/app/cash/redwood/treehouse/TreehouseAppContentTest.kt]: I added an event for this so I can tell when we’re receiving new code and when we’re not. In this test it’s not that interesting!

File: redwood-treehouse-host/src/commonTest/kotlin/app/cash/redwood/treehouse/CodeHostTest.kt [hunk 4]
```diff
@@ -0,0 +1,244 @@
...
+    eventLog.takeEvent("codeSessionA.app.uis[0].start()")
+
+    codeHost.stop()
+    eventLog.takeEvent("codeSessionA.app.uis[0].close()")
+    eventLog.takeEvent("codeSessionA.cancel()")
+
+    content.unbind()
+  }
+
+  /** CodeHost doesn't have to stay resident forever. */
```
Comment (swankjesse) [inline redwood-treehouse-host/src/commonTest/kotlin/app/cash/redwood/treehouse/CodeHostTest.kt:96]: This is probably the most exciting thing about the PR. We can now shut down a Zipline completely and start it up again. That’ll be potentially great for saving memory.

**Comment by swankjesse** [comment]
# ⚠️ stacked PR!

File: redwood-treehouse-host/src/commonMain/kotlin/app/cash/redwood/treehouse/TreehouseApp.kt [hunk 5]
```diff
@@ -62,7 +71,7 @@ public class TreehouseApp<A : AppService> private constructor(
    * instance may be replaced if new code is loaded.
    */
   public val zipline: Zipline?
-    get() = codeHost.session?.zipline
+    get() = (codeHost.codeSession as? ZiplineCodeSession)?.zipline
```
Comment (veyndan) [inline redwood-treehouse-host/src/commonMain/kotlin/app/cash/redwood/treehouse/TreehouseApp.kt:74]: Is `codeSession` not being a `ZiplineCodeSession` valid?

If not, perhaps we can make `CodeSession` itself a type parameter?

File: redwood-treehouse-host/src/commonMain/kotlin/app/cash/redwood/treehouse/CodeHost.kt [hunk 6]
```diff
@@ -15,16 +15,184 @@
...
+    ) : State<A>()
+
+    class Starting<A : AppService>(
+      override val codeUpdatesScope: CoroutineScope,
+    ) : State<A>()
+
+    class Crashed<A : AppService>(
+      override val codeUpdatesScope: CoroutineScope,
+    ) : State<A>()
+  }
```
Comment (veyndan) [inline redwood-treehouse-host/src/commonMain/kotlin/app/cash/redwood/treehouse/CodeHost.kt:195]: Personally, I would've loved to see the states hoisted inside the respective states, in order to get the true benefits of making a state machine (i.e., it being easy to follow how one state gets to the next, a thing which is still difficult in this PR).

Apologies if that was a planned follow up!

**Review by veyndan — APPROVED** [review]

File: redwood-treehouse-host/src/commonMain/kotlin/app/cash/redwood/treehouse/CodeHost.kt (hunk 6 above)
Comment (swankjesse) [reply redwood-treehouse-host/src/commonMain/kotlin/app/cash/redwood/treehouse/CodeHost.kt:195]: Yeah lemme explore that in follow up.

File: redwood-treehouse-host/src/commonMain/kotlin/app/cash/redwood/treehouse/TreehouseApp.kt (hunk 5 above)
Comment (swankjesse) [reply redwood-treehouse-host/src/commonMain/kotlin/app/cash/redwood/treehouse/TreehouseApp.kt:74]: Lemme explore that in follow up!

File: redwood-treehouse-host/src/commonMain/kotlin/app/cash/redwood/treehouse/CodeHost.kt (hunk 6 above)
Comment (swankjesse) [reply redwood-treehouse-host/src/commonMain/kotlin/app/cash/redwood/treehouse/CodeHost.kt:195]: A month later . . . we looked into this, and didn’t find something I loved!

@veyndan if you’d like to run with this, please do!
